name: Secure Container Supply Chain
run-name: ${{ github.actor }} pipeline
on: [push]
jobs:
  Build-and-Check-Image:
    permissions:
        actions: read
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: docker build -t docker.io/abdelhak245/simple-go:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'docker.io/abdelhak245/simple-go:${{ github.sha }}'
          format: 'json'
          exit-code: '1'
          output: 'scan-report.json'
          ignore-unfixed: false
      - name: Scan image and generate SBOM
        uses: anchore/sbom-action@v0
        with:
            image: docker.io/abdelhak245/simple-go:${{ github.sha }}
            format: spdx-json
            output-file: sbom.spdx.json
      - name: Set up cosign
        uses: sigstore/cosign-installer@main
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-go:${{ github.sha }}
      - name: sign container image
        run: |
            cosign sign --key env://COSIGN_KEY docker.io/abdelhak245/simple-go:${{ github.sha }}
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
      - name: Check images
        run: |
          docker pull docker.io/abdelhak245/simple-go:${{ github.sha }}
          cosign verify --key cosign.pub docker.io/abdelhak245/simple-go:${{ github.sha }} 